FROM python:3.8

RUN echo "version 1.0"

WORKDIR /home/ubuntu/

RUN git clone -b develop https://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@github.com/kweonminsung/enlistpedia.git

WORKDIR /home/ubuntu/enlistpedia/backend/

RUN python -m venv venv

RUN . venv/Scripts/activate

RUN pip install -r requirements.txt

EXPOSE 3001

CMD uvicorn main:app --host 0.0.0.0 --port 3001